# Generated by Django 5.0.7 on 2024-11-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sub_county',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
