# Generated by Django 5.0.7 on 2024-11-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='facilitator_id',
            new_name='facilitator',
        ),
    ]
