# Generated by Django 5.0.7 on 2024-11-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kicd', '0001_initial'),
        ('module', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('total_marks', models.IntegerField()),
                ('assessment_duration', models.IntegerField()),
                ('kicd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kicd.kicd')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
