# Generated by Django 5.0.7 on 2024-11-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tsc_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(max_length=100)),
                ('teachers_id', models.IntegerField()),
            ],
        ),
    ]
